sudo: required
dist: trusty
language: cpp

branches:
  only:
    - master

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-3.7
            - libc++-dev
      env: COMPILER=clang++-3.7

before_install:
  - sudo config/ci/build_deps.sh

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make tests
  - cd ..

env:
  global:
  - ENCRYPTION_LABEL: c0be4061fc5e
  - COMMIT_AUTHOR_EMAIL: bastani.vahid@gmail.com

deploy:
  provider: script
  script: config/ci/doc/deploy.sh
  on:
    branch: master
