language: generic # don't install any environment

script:
  - ls

env:
  global:
  - ENCRYPTION_LABEL: "c2b11fe6566c"
  - COMMIT_AUTHOR_EMAIL: "bastani.vahid@gmail.com"

deploy:
  provider: script
  script: config/ci/doc/deploy.sh
  on:
    branch: doc-ci
