language: generic

env:
  global:
  - ENCRYPTION_LABEL: c0be4061fc5e
  - COMMIT_AUTHOR_EMAIL: bastani.vahid@gmail.com

deploy:
  provider: script
  script: config/ci/doc/deploy.sh
  on:
    branch: master
