sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
          env: COMPILER=g++-4.9
    - complier: clang
      addson:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
          env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-test-dev

env:
  global:
  - ENCRYPTION_LABEL: c0be4061fc5e
  - COMMIT_AUTHOR_EMAIL: bastani.vahid@gmail.com

deploy:
  provider: script
  script: config/ci/doc/deploy.sh
  on:
    branch: master
